# This is a basic workflow to help you get started with Actions
name: Java CI with Maven

on:
  push:
    branches:
      - master
      - issue-*

permissions:
    statuses: write
    checks: write
    contents: write
    pull-requests: write

jobs:
  build:
    name: Build and Test  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Start restful booker service
      run: docker compose -f ./docker-compose-restfulbooker.yml up -d

    - name: Start restful ecommerce service
      run: docker compose -f ./docker-compose-ecommerce.yml up -d

    - name: Build Project
      run: mvn clean install -DskipTests

    - name: Run tests
      run: mvn clean test

    - name: Stop restful booker service
      run: docker compose -f ./docker-compose-restfulbooker.yml down --remove-orphans

    - name: Stop restful ecommerce service
      run: docker compose -f ./docker-compose-ecommerce.yml down --remove-orphans

    - name: Test Reporter
      uses: dorny/test-reporter@v1.6.0
      if: always()
      with:
        name: Test Results
        path: target/surefire-reports/TEST-TestSuite.xml
        reporter: java-junit
